### ISSUE TITLE
doesnt load mobs spawned by mob spawners

### ISSUE THREAD

**Issue by firstfractal** [tratteo/LiterallyChunkLoader-1.15#2]

**Comment by tratteo** [comment]
From the Wiki: "The spawner spawns mobs in a 9×3×9 area (see § Mechanics) around it when the player is within 16 blocks". Thus, the player needs to be in range.

**Comment by Tiebe** [comment]
Is it because you have no time, or because it's too hard? Would I be allowed to make a pull request and see if I can make it work?

**Comment by tratteo** [comment]
Actually, i could dig more into this to see if i can make it work. However, since the beginning i decided not to include mob spawning in force loaded chunks for two main reasons:
1. Lag: as i saw, many people just place loaders and forget about them, this could cause in massive lag spikes since mobs would spawn even in the farthest chunks.
2. Mob caps: mob caps would be affected by mobs spawning in force loaded chunks
3. Vanilla: i wanted to make this loader vanilla friendly. Including mob spawning in force loaded chunks would go against this vision of mine. In fact, all afk farms would be possible without even be afk and furthermore, complicated things such as mob switches would be almost possible by just forceloading enough chunks in order to cap mobcaps in the whole server

**Comment by Tiebe** [comment]
That would be awesome, thank you very much :D

**Comment by tratteo** [comment]
However, i don't have much time, so if you really want you can always clone and if it works make a pull request, I'll check if that fits within my view of this mod. Can't assure you i'll actually merge it in case it doesn't :D
